export enum TipoUsuario {
  ADMINISTRADOR = 'ADMINISTRADOR',
  FATURISTA = 'FATURISTA',
  ESTOQUISTA = 'ESTOQUISTA',
  ANALISTA_CREDITO = 'ANALISTA_CREDITO',
  CONTAS_RECEBER = 'CONTAS_RECEBER',
  CONTAS_PAGAR = 'CONTAS_PAGAR',
}

export enum TipoEstoque {
  TODOS = 0,
  MATRIZ = 1,
  HF = 10000006,
}
